baseurl = "https://exuanbo.xyz"
title = "Exuanbo's"
description = "大杂烩般的个人博客"
languageCode = "zh-CN"
defaultcontentlanguage = "zh"

relativeURLs = true
rssLimit = 10
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true

[taxonomies]
  tag = "tags"

[params]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2

[language.zh]
  languageName = "Chinese"
  weight = 1

[language.en]
  languageName = "English"
  weight = 2

# Menu links
[[languages.zh.menu.main]]
  name = "首页"
  url = "/"
  weight = 1
[[languages.zh.menu.main]]
  name = "关于"
  url = "/about/"
  weight = 2
[[languages.zh.menu.main]]
  name = "订阅"
  url = "https://exuanbo.xyz/index.xml"
  weight = 3

[[language.en.menu.main]]
  name = "HOME"
  url = "/"
  weight = 1
[[language.en.menu.main]]
  name = "ABOUT"
  url = "/about/"
  weight = 2
[[language.en.menu.main]]
  name = "RSS"
  url = "https://exuanbo.xyz/index.xml"
  weight = 3
