baseurl = "https://exuanbo.xyz"
title = "Exuanbo's"
languageCode = "zh-CN"
defaultcontentlanguage = "zh"

relativeURLs = true
rssLimit = 10
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true

[taxonomies]
  tag = "tags"

[params]
  footer = "&copy; 2019 [Exuanbo's](https://exuanbo.xyz)"
  copyright = "License: [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2

[language.zh]
  languageName = "Chinese"
  weight = 1

[language.en]
  languageName = "English"
  weight = 2

# Menu links
[[languages.zh.menu.main]]
  name = "首页"
  url = "/"
  weight = 1
[[languages.zh.menu.main]]
  name = "关于"
  url = "/about/"
  weight = 2
[[languages.zh.menu.main]]
  name = "订阅"
  url = "https://exuanbo.xyz/index.xml"
  weight = 3

[[language.en.menu.main]]
  name = "HOME"
  url = "/"
  weight = 1
[[language.en.menu.main]]
  name = "ABOUT"
  url = "/about/"
  weight = 2
[[language.en.menu.main]]
  name = "RSS"
  url = "https://exuanbo.xyz/index.xml"
  weight = 3
