baseurl = "https://exuanbo.xyz"
title = "Exuanbo's"
languageCode = "en"

relativeURLs = true
rssLimit = 10
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true

[taxonomies]
  tag = "tags"

[params]
  description = "Exuanbo's landing page"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
  [markup.tableOfContents]
    startLevel = 2

[menu]
  [[menu.main]]
    name = "POSTS"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "ABOUT"
    url = "/about/"
    weight = 3
