baseurl = "https://exuanbo.xyz"
title = "Exuanbo's"
languagecode = "zh"
defaultcontentlanguage = "zh"

relativeURLs = true
rssLimit = 10
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true

pygmentsuseclasses = true
pygmentscodefences = true

[taxonomies]
  tag = "tags"

[params]
  footer = "&copy; 2019 [Exuanbo](https://exuanbo.xyz)"
  copyright = "License: [CC BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/)"
  isso = false
  valine = true

# Menu links
[[menu.main]]
  name = "WRITINGS"
  url = "/"
  weight = 1
[[menu.main]]
  name = "ABOUT"
  url = "/about/"
  weight = 2
[[menu.main]]
  name = "WIKI"
  url = "https://wiki.exuanbo.xyz"
  weight = 3

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false
[outputs]
  page = ["HTML","MarkDown"]