name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup PostCSS for Hugo
        run: |
          npm install -g postcss-cli autoprefixer
          npm ci

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.1'
          extended: true

      - name: Build
        run: |
          hugo
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          external_repository: exuanbo/exuanbo.github.io
          publish_branch: master
